/* Automatically generated by
	ThreadedFFIPlugin VMMaker.oscogLLP64-nice.1926 uuid: 0a431195-4bae-0e42-a1f5-5a17d010c24d
 */

#if defined(__ARM_ARCH__) || defined(__arm__) || defined(__arm32__) || defined(ARM32)

# define ARM32FFIPlugin_exports SqueakFFIPrims_exports
# include "ARM32FFIPlugin.c"

#elif defined(_M_I386) || defined(_X86_) || defined(i386) || defined(i486) || defined(i586) || defined(i686) || defined(__i386__) || defined(__386__) || defined(X86) || defined(I386)

# define IA32FFIPlugin_exports SqueakFFIPrims_exports
# include "IA32FFIPlugin.c"

#elif !defined(WIN64) && (defined(x86_64) || defined(__amd64) || defined(__x86_64) || defined(__amd64__) || defined(__x86_64__))

# define X64SysVFFIPlugin_exports SqueakFFIPrims_exports
# include "X64SysVFFIPlugin.c"

#elif defined(WIN64) && (defined(x86_64) || defined(__amd64) || defined(__x86_64) || defined(__amd64__) || defined(__x86_64__) || defined(_M_AMD64) || defined(_M_X64))

# define X64Win64FFIPlugin_exports SqueakFFIPrims_exports
# include "X64Win64FFIPlugin.c"

#else
# error As yet no FFI implementation appears to exist for your platform.
# error Consider implementing it, starting by adding a subclass of ThreadedFFIPlugin.
#endif
