/* Automatically generated by
	CCodeGeneratorGlobalStructure VMMaker.oscogLLP64-nice.1919 uuid: 67128742-82db-1c4a-a5e7-f1f7a5cee80c
 */

#define VM_PROXY_MAJOR 1
#define VM_PROXY_MINOR 13

#define SQ_VI_BYTES_PER_WORD 8

#define BaseHeaderSize 8
#define BytesPerOop 8
#define BytesPerWord 8

#define PrimErrGenericFailure 1
#define PrimErrBadReceiver 2
#define PrimErrBadArgument 3
#define PrimErrBadIndex 4
#define PrimErrBadNumArgs 5
#define PrimErrInappropriate 6
#define PrimErrUnsupported 7
#define PrimErrNoModification 8
#define PrimErrNoMemory 9
#define PrimErrNoCMemory 10
#define PrimErrNotFound 11
#define PrimErrBadMethod 12
#define PrimErrNamedInternal 13
#define PrimErrObjectMayMove 14
#define PrimErrLimitExceeded 15
#define PrimErrObjectIsPinned 16
#define PrimErrWritePastObject 17

#define MinSmallInteger -1152921504606846976
#define MaxSmallInteger 1152921504606846975

#define STACKVM 1
#define SPURVM 1
#define COGVM 1
#if !defined(COGMTVM)
#	define COGMTVM 0
#endif

#define DisownVMLockOutFullGC 1
