/* Automatically generated by
	CCodeGenerator VMMaker.oscogLLP64-nice.1920 uuid: c1c7e816-a15c-6a4d-b25d-7cc5ef4f0cb2
 */

typedef struct {
	sqInt	classTag;
	sqInt	enclosingObject;
	sqInt	target;
	sqInt	selector;
	sqInt	numArgs;
	sqInt	depth;
 } NSSendCache;
