/* Automatically generated by
	CCodeGenerator VMMaker.oscogLLP64-nice.1919 uuid: 67128742-82db-1c4a-a5e7-f1f7a5cee80c
 */

typedef struct {
	sqInt	classTag;
	sqInt	enclosingObject;
	sqInt	target;
	sqInt	selector;
	sqInt	numArgs;
	sqInt	depth;
 } NSSendCache;
